### ISSUE TITLE
Contact form not submitting 

### ISSUE THREAD

**Issue by wibb36** [josmithua/website#10]
Hi Joshua! 

I tried to send you an email on https://josmithua.dev/contact

and this is the error I'm getting: 

`
Error: You made a POST request to https://josmithua.dev/contact but did not provide an `action` for route "routes/contact", so there is no way to handle the request.
    at Object.callRouteAction (/var/task/node_modules/@remix-run/server-runtime/data.js:30:11)
    at renderDocumentRequest (/var/task/node_modules/@remix-run/server-runtime/server.js:216:35)
    at requestHandler (/var/task/node_modules/@remix-run/server-runtime/server.js:55:26)
    at /var/task/node_modules/@remix-run/netlify/server.js:31:26
    at Runtime.exports.handler (/var/task/netlify/functions/server/index.js:24:67)
    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)
`

**Comment by josmithua** [comment]
Thanks Sam,

I guess netlify forms aren't working nicely with remix yet. In the meantime I've linked to my twitter instead.

**Comment by wibb36** [comment]
remix works well with Vercel.

**Comment by josmithua** [comment]
Remix works well with Netlify as well, except integrating with Netlify Forms requires a gross workaround which I didn't want to implement. They are working on a solution though. 

If you have twitter, you can shoot me a DM there, @josmithua. Otherwise, you can email "js at joshuasmith dot ca"
